AllCops:
  Exclude:
    - 'test.rb'
    - 'fizzbuzz.rb'
    - 'interp.rb'
Style/SelfAssignment:
  Enabled: false
Style/HashSyntax:
  EnforcedStyle: hash_rockets
Style/WordArray:
  EnforcedStyle: brackets